version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: skariga_app
    network_mode: "host"
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - .:/var/www
      - /var/www/vendor/
    environment:
      - APP_ENV=production
      - APP_DEBUG=false
    networks:
      - skariga_network

  webserver:
    image: nginx:alpine
    container_name: skariga_webserver
    network_mode: "host"
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - .:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - skariga_network

networks:
  skariga_network:
    driver: bridge
